# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Z3Z42Z0TBYaNIb7uBXgDQNhFTgK98sP
"""

import streamlit as st
import pandas as pd
import pickle
import numpy as np

# -------------------------------
# Load model and feature list
# -------------------------------
with open("logistic_model.pkl", "rb") as file:
    model = pickle.load(file)

with open("feature_columns.pkl", "rb") as file:
    feature_columns = pickle.load(file)

# -------------------------------
# Streamlit Page Config
# -------------------------------
st.set_page_config(
    page_title="Customer Conversion Prediction",
    layout="wide"
)

st.title("📊 Customer Purchase Prediction Dashboard")
st.markdown(
    "This application predicts the **probability of purchase** "
    "based on user behavioral and session attributes."
)

# -------------------------------
# Sidebar Inputs
# -------------------------------
st.sidebar.header("User Input Features")

user_input = {}

for feature in feature_columns:
    user_input[feature] = st.sidebar.number_input(
        label=feature,
        value=0.0,
        step=0.1
    )

input_df = pd.DataFrame([user_input])

# -------------------------------
# Prediction Section
# -------------------------------
st.subheader("🔮 Prediction Result")

if st.button("Predict Purchase Probability"):
    prediction_prob = model.predict(input_df)[0]

    st.metric(
        label="Predicted Purchase Probability",
        value=f"{prediction_prob:.2%}"
    )

    if prediction_prob >= 0.5:
        st.success("✅ High likelihood of purchase")
    else:
        st.warning("⚠️ Low likelihood of purchase")

# -------------------------------
# Show Input Data
# -------------------------------
with st.expander("📄 View Input Data"):
    st.dataframe(input_df)